"""
prism_reviewer.agents.state
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Defines the shared LangGraph StateGraph schema for the PrismReviewer review
pipeline.

The ``ReviewState`` TypedDict is the single source of truth for all data that
flows between nodes.  Every field is explicitly typed — no ``Any`` on input
fields.  The ``raw_findings`` field uses ``operator.add`` as a LangGraph
reducer so that the three parallel agent branches can safely append their
results without overwriting each other.
"""

import operator
from typing import Annotated, Any, Dict, List, Literal

from typing_extensions import NotRequired, TypedDict


class Finding(TypedDict):
    """Represents a single structured code-review finding emitted by an agent node."""

    file: str
    """Relative path of the file, exactly as it appears in the diff header."""

    line: int
    """1-indexed line number in the new version of the file."""

    severity: Literal["CRITICAL", "MAJOR", "ADVISORY"]
    """
    Impact tier of the finding:
    - CRITICAL  → must block the merge.
    - MAJOR     → strongly expected to be addressed before merge.
    - ADVISORY  → informational; never blocks pipeline progress.
    """

    agent: str
    """Name of the agent that produced this finding: warden | architect | inspector."""

    message: str
    """Precise, single-sentence description of the issue and why it matters."""

    signature: str
    """SHA-256 content hash used for idempotent cross-run deduplication."""


class ReviewState(TypedDict):
    """
    Shared state dictionary that flows through the LangGraph StateGraph.

    Fields are grouped by lifecycle phase:

    **Input context** — populated once by ``build_context_node``, then
    read (never written) by the three parallel agent nodes.

    **Fan-out accumulator** — ``raw_findings`` uses the ``operator.add``
    reducer so that all three parallel branches safely append their lists
    without overwriting each other.

    **Post-verification** — populated by ``verifier_node`` after dropping
    hallucinated or duplicate findings.

    **Final output** — ``report_markdown`` populated by ``aggregator_node``.
    """

    # ── Input context ────────────────────────────────────────────────────────
    repo_path: str
    """Absolute path to the repository root on disk."""

    git_diff: str
    """Raw unified diff string (e.g., from ``git diff``)."""

    pr_title: str
    """Pull request title (empty string for local runs without a PR number)."""

    pr_id: NotRequired[int | str]
    """Pull request ID or number (optional)."""

    pr_description: str
    """Pull request description/body (empty string for local runs)."""

    repo_structure: str
    """Flat list of files tracked by git (capped at 100 lines)."""

    ast_map: Dict[str, Any]
    """
    Mapping of relative file path → AST skeleton dict from
    ``UniversalASTAnalyzer.get_ast_skeleton()``.  Populated by
    ``build_context_node``.
    """

    codelens_dep_summary: str
    """Serialised output of ``scan_dependencies()``.  Populated by ``build_context_node``."""

    codelens_search_hits: str
    """Cross-reference search hits for touched module names.  Populated by ``build_context_node``."""

    context_content: str
    """Contents of ``.prism_reviewer/context.md`` if present, else empty string."""

    readme_content: NotRequired[str]
    """Contents of repository root ``README.md`` (truncated if exceeding max_readme_chars), else empty string."""

    rules_content: str
    """Contents of ``.prism_reviewer/rules.md`` if present, else empty string."""

    previous_signatures: List[str]
    """
    Signatures from the previous run (loaded from ``.prism_reviewer/signatures.json``).
    Stored as a list for JSON-serializability; converted to a set inside ``verifier_node``
    for O(1) lookup.
    """

    diff_mode: NotRequired[str]
    """Diff mode used for the review: 'full', 'incremental', or 'auto'."""

    is_incremental: NotRequired[bool]
    """Whether the current review diff is incremental (comparing previous commit to HEAD)."""

    full_pr_files: NotRequired[List[str]]
    """List of all files modified across the full PR (used for PR-wide context in incremental mode)."""


    regions: List[Dict[str, Any]]
    """
    List of review regions generated by partitioning the unified diff.
    Each region dictionary contains:
    - files: List[str] (names of files grouped in this region)
    - diff: str (the portion of the git diff for these files)
    - line_count: int (total lines in the diff)
    - region_index: int (1-indexed index of this region)
    - total_regions: int (total number of regions)
    """

    current_region: NotRequired[Dict[str, Any]]
    """The current region info being processed by the agent node during dynamic fan-out."""

    # ── Fan-out accumulator ──────────────────────────────────────────────────
    raw_findings: Annotated[List[Finding], operator.add]
    """
    Findings emitted by all agent nodes.  Uses ``operator.add`` as a LangGraph
    reducer so parallel branches safely append without overwriting each other.
    After all three agents complete, this contains the combined, unfiltered list.
    """

    node_log_blocks: NotRequired[Annotated[List[Dict[str, Any]], operator.add]]
    """
    Buffered log blocks emitted by parallel agent nodes.  Uses ``operator.add``
    as a LangGraph reducer so parallel branches safely append log blocks.
    Flushed sequentially in rank order at the verifier node.
    """

    # ── Post-verification ────────────────────────────────────────────────────
    verified_findings: List[Finding]
    """Findings that passed the hallucination guard and deduplication filter."""

    resolved_signatures: NotRequired[List[str]]
    """
    Signatures of findings whose corresponding GitHub inline comment thread has
    been manually resolved by a reviewer (via the "Resolve conversation" button
    in the GitHub UI).  Populated by the GitHub publishing layer before the
    aggregator renders the report.  When present, these findings are shown in a
    separate ✅ Resolved section rather than the active findings table.
    """

    # ── Final output ─────────────────────────────────────────────────────────
    report_markdown: str
    """Fully rendered Markdown review report, ready to write to disk or post to GitHub."""
